services:
  database:
    image: postgres:latest
    container_name: todo_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5800:5432
    volumes:
      - pgdata:/var/lib/postgress/database

  db-test:
    image: postgres:latest
    container_name: test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 6543:5432

volumes:
  pgdata:
